name: Build and Release FeatherCapeJump

on:
  push:
    branches:
      - master # Triggers on pushes to the master branch
    # tags:
    #  - 'v*' # Temporarily disabled, will be re-enabled later

jobs:
  build:
    name: Build .NET Project
    runs-on: windows-latest # Using windows-latest as it's a .NET Framework project
    permissions:
      contents: read # To checkout the code

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          # Using .NET SDK 7.x which supports .NET Framework 4.7.2
          dotnet-version: '7.0.x'

      - name: Prepare Build Libraries from _GameOriginalLibs
        shell: powershell
        run: |
          $sourceDir = "${{ github.workspace }}/_GameOriginalLibs"
          $destinationDir = "${{ github.workspace }}/BuildReferencedLibs"
          Write-Host "Source for DLLs: $sourceDir"
          Write-Host "Destination for build DLLs: $destinationDir"
          if (Test-Path $sourceDir) {
            New-Item -ItemType Directory -Force -Path $destinationDir
            Copy-Item -Path "$sourceDir/*" -Destination $destinationDir -Force -Recurse
            Write-Host "Copied DLLs from $sourceDir to $destinationDir"
          } else {
            Write-Error "_GameOriginalLibs folder not found. Please create it in your repository and commit the necessary game/modding DLLs there."
            exit 1
          }
        working-directory: '${{ github.workspace }}'

      - name: Restore dependencies
        run: dotnet restore FeatherCapeJump.sln
        working-directory: '${{ github.workspace }}'

      - name: Get version
        id: get_version
        run: |
          if ("${{ github.ref_type }}" -eq "tag") {
            $REF_NAME = "${{ github.ref_name }}"
            if ($REF_NAME.StartsWith("v")) {
              $VERSION = $REF_NAME.Substring(1)
            } else {
              $VERSION = $REF_NAME
            }
          } else {
            # For non-tag pushes (e.g., to master)
            $SHORT_SHA = "${{ github.sha }}".Substring(0, 7)
            $VERSION = "0.0.0-dev-$SHORT_SHA"
          }
          Write-Host "Detected version: $VERSION"
          echo "version=$VERSION" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
        shell: powershell

      - name: Build project
        run: >
          dotnet build FeatherCapeJump.sln --configuration Release --no-restore
          /p:Version=${{ steps.get_version.outputs.version }}
          /p:AssemblyVersion=${{ steps.get_version.outputs.version }}
          /p:FileVersion=${{ steps.get_version.outputs.version }}
        working-directory: '${{ github.workspace }}'
        shell: powershell

      - name: Upload DLL artifact
        uses: actions/upload-artifact@v4
        with:
          name: FeatherCapeJump-dll
          # Path to the DLL. Based on your structure, it's under net472 for Release.
          path: '${{ github.workspace }}/bin/Release/net472/FeatherCapeJump.dll'

  create_release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    # Only create a release if it's a tag push
    if: github.ref_type == 'tag'
    steps:
      - name: Download DLL artifact
        uses: actions/download-artifact@v4
        with:
          name: FeatherCapeJump-dll
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            Automated release for ${{ github.ref_name }}.
            The `FeatherCapeJump.dll` is attached below.

            **Changelog:**
            *(Consider maintaining a CHANGELOG.md file and linking it here, or list changes manually for each release)*
          draft: false
          prerelease: false
          files: |
            artifacts/FeatherCapeJump.dll
